[package]
name = "rust"
version = "1.0.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
godot = "0.3.2"
rand = "0.9.1"
rand_distr = "0.5.1"

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.
